version: "2"
services:

  mysql:
    image: mysql:5.7.26
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_DATABASE=local
      - MYSQL_USER=local
      - MYSQL_PASSWORD=local
    ports:
      - ${DB_PORT}:3306
    volumes:
      - db:/var/lib/mysql/
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-time-zone='+3:00' --innodb-flush-log-at-trx-commit=2

volumes:
  db:
  db24:
  docroot24:
